### ISSUE TITLE
[ISSUE] cannot load such file -- dry-types (LoadError)

### ISSUE THREAD

**Issue by columbian-chris** [truemail-rb/truemail-rack#104]
### New issue checklist

- [x] I have updated `truemail-rack` to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/truemail-rb/truemail-rack/blob/master/CONTRIBUTING.md)
- [x] I have read the [documentation](https://truemail-rb.org/truemail-rack)
- [x] I have searched for [existing GitHub issues](https://github.com/truemail-rb/truemail-rack/issues)

### Issue description

Did a fresh install of rack and this package and ran into this error starting up:

```
$ VERIFIER_EMAIL=myemail@example.com ACCESS_TOKENS=a262d915-15bc-417c-afeb-842c63b54154 rackup
Traceback (most recent call last):
	20: from /usr/local/bin/rackup:23:in `<main>'
	19: from /usr/local/bin/rackup:23:in `load'
	18: from /var/lib/gems/2.7.0/gems/rackup-2.1.0/bin/rackup:5:in `<top (required)>'
	17: from /var/lib/gems/2.7.0/gems/rackup-2.1.0/lib/rackup/server.rb:182:in `start'
	16: from /var/lib/gems/2.7.0/gems/rackup-2.1.0/lib/rackup/server.rb:325:in `start'
	15: from /var/lib/gems/2.7.0/gems/rackup-2.1.0/lib/rackup/server.rb:382:in `handle_profiling'
	14: from /var/lib/gems/2.7.0/gems/rackup-2.1.0/lib/rackup/server.rb:326:in `block in start'
	13: from /var/lib/gems/2.7.0/gems/rackup-2.1.0/lib/rackup/server.rb:424:in `wrapped_app'
	12: from /var/lib/gems/2.7.0/gems/rackup-2.1.0/lib/rackup/server.rb:263:in `app'
	11: from /var/lib/gems/2.7.0/gems/rackup-2.1.0/lib/rackup/server.rb:354:in `build_app_and_options_from_config'
	10: from /var/lib/gems/2.7.0/gems/rack-3.0.8/lib/rack/builder.rb:64:in `parse_file'
	 9: from /var/lib/gems/2.7.0/gems/rack-3.0.8/lib/rack/builder.rb:94:in `load_file'
	 8: from /var/lib/gems/2.7.0/gems/rack-3.0.8/lib/rack/builder.rb:103:in `new_from_string'
	 7: from /var/lib/gems/2.7.0/gems/rack-3.0.8/lib/rack/builder.rb:103:in `eval'
	 6: from /srv/www/sandbox/public_html/test/truemail-rack/config.ru:7:in `block in <main>'
	 5: from /srv/www/sandbox/public_html/test/truemail-rack/config.ru:7:in `require_relative'
	 4: from /srv/www/sandbox/public_html/test/truemail-rack/config/loader.rb:3:in `<top (required)>'
	 3: from /srv/www/sandbox/public_html/test/truemail-rack/config/loader.rb:3:in `require_relative'
	 2: from /srv/www/sandbox/public_html/test/truemail-rack/config/system/types.rb:3:in `<top (required)>'
	 1: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require': cannot load such file -- dry-types (LoadError)
```

**Comment by bestwebua** [comment]
Hello, @columbian-chris Have you run `bundle install` before it? Seems everything is okay.

<img width="1728" alt="Screenshot 2023-11-14 at 7 38 49 AM" src="https://github.com/truemail-rb/truemail-rack/assets/14002692/0327224d-4a88-4de9-9ecd-f09e31b493f1">
